// apps/kodidocs/components/primitives/box/box.tsx
import React from "react"
import { type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

import { boxVariants } from "./variants"

export type BoxProps = React.HTMLAttributes<HTMLDivElement> &
  VariantProps<typeof boxVariants> & {
    as?: "div" | "h1" | "h2" | "h3" | "h4" | "p" | "span"
  }

const Box = React.forwardRef<HTMLDivElement, BoxProps>(
  (
    {
      absolute,
      align,
      aspect,
      autoCols,
      autoRows,
      backdropBlur,
      backdropBrightness,
      backdropContrast,
      backdropGrayscale,
      backdropInvert,
      backdropOpacity,
      backdropSaturate,
      backdropSepia,
      basis,
      bg,
      bgAttachment,
      bgBlend,
      bgClip,
      bgImage,
      bgOrigin,
      bgPosition,
      bgRepeat,
      bgSize,
      block,
      blur,
      borderCollapse,
      borderColor,
      borderSpacing,
      borderSpacingX,
      borderSpacingY,
      borderStyle,
      borderWidth,
      borderWidthB,
      borderWidthL,
      borderWidthR,
      borderWidthT,
      borderWidthX,
      borderWidthY,
      bottom,
      brightness,
      capitalize,
      caption,
      colEnd,
      colSpan,
      colStart,
      columns,
      content,
      contents,
      contrast,
      cursor,
      decoration,
      decorationColor,
      decorationStyle,
      decorationThickness,
      delay,
      display,
      dropShadow,
      duration,
      fixed,
      flex,
      flexDirection,
      floats,
      fontFamily,
      fontSize,
      fontSmoothing,
      fontStyle,
      fontVariantNumeric,
      fontWeight,
      gap,
      gapX,
      gapY,
      gradientFromStop,
      gradientToStop,
      gradientViaStop,
      grayscale,
      grid,
      gridCols,
      gridFlow,
      gridRows,
      grow,
      h,
      hidden,
      hueRotate,
      hyphens,
      indent,
      inline,
      inlineBlock,
      inlineFlex,
      inlineGrid,
      invert,
      italic,
      items,
      justify,
      justifyItems,
      justifySelf,
      leading,
      left,
      lineClamp,
      lineThrough,
      listItem,
      listStyleImage,
      listStylePosition,
      listStyleType,
      lowercase,
      m,
      maxH,
      maxW,
      minH,
      minW,
      mixBlend,
      noUnderline,
      normalCase,
      object,
      objectPosition,
      opacity,
      order,
      origin,
      overflow,
      overflowX,
      overflowY,
      overline,
      overscroll,
      overscrollX,
      overscrollY,
      p,
      pb,
      pl,
      placeContent,
      placeItems,
      placeSelf,
      pointerEvents,
      position,
      pr,
      pt,
      px,
      py,
      relative,
      right,
      rotate,
      rounded,
      roundedB,
      roundedBl,
      roundedBr,
      roundedL,
      roundedR,
      roundedT,
      roundedTl,
      roundedTr,
      rowEnd,
      rowSpan,
      rowStart,
      saturate,
      scale,
      scrollBehavior,
      scrollM,
      scrollMB,
      scrollME,
      scrollML,
      scrollMR,
      scrollMS,
      scrollMT,
      scrollMX,
      scrollMY,
      scrollP,
      scrollPB,
      scrollPE,
      scrollPL,
      scrollPR,
      scrollPS,
      scrollPT,
      scrollPX,
      scrollPY,
      select,
      self,
      sepia,
      shadow,
      shadowColor,
      shrink,
      skewX,
      skewY,
      snapAlign,
      snapStop,
      snapType,
      sticky,
      table,
      text,
      textAlign,
      textClip,
      textEllipsis,
      textOverflow,
      textTransform,
      top,
      touch,
      tracking,
      transition,
      transitionTimingFunction,
      translateX,
      translateY,
      truncate,
      underline,
      underlineOffset,
      uppercase,
      visibility,
      w,
      whitespace,
      willChange,
      wordBreak,
      wrap,
      z,
      as,
      className,
      ...props
    },
    ref
  ) => {
    const Ele = as ? as : "div"
    return (
      <Ele
        className={cn(
          boxVariants({
            absolute,
            align,
            aspect,
            autoCols,
            autoRows,
            backdropBlur,
            backdropBrightness,
            backdropContrast,
            backdropGrayscale,
            backdropInvert,
            backdropOpacity,
            backdropSaturate,
            backdropSepia,
            basis,
            bg,
            bgAttachment,
            bgBlend,
            bgClip,
            bgImage,
            bgOrigin,
            bgPosition,
            bgRepeat,
            bgSize,
            block,
            blur,
            borderCollapse,
            borderColor,
            borderSpacing,
            borderSpacingX,
            borderSpacingY,
            borderStyle,
            borderWidth,
            borderWidthB,
            borderWidthL,
            borderWidthR,
            borderWidthT,
            borderWidthX,
            borderWidthY,
            bottom,
            brightness,
            capitalize,
            caption,
            colEnd,
            colSpan,
            colStart,
            columns,
            content,
            contents,
            contrast,
            cursor,
            decoration,
            decorationColor,
            decorationStyle,
            decorationThickness,
            delay,
            display,
            dropShadow,
            duration,
            fixed,
            flex,
            flexDirection,
            floats,
            fontFamily,
            fontSize,
            fontSmoothing,
            fontStyle,
            fontVariantNumeric,
            fontWeight,
            gap,
            gapX,
            gapY,
            gradientFromStop,
            gradientToStop,
            gradientViaStop,
            grayscale,
            grid,
            gridCols,
            gridFlow,
            gridRows,
            grow,
            h,
            hidden,
            hueRotate,
            hyphens,
            indent,
            inline,
            inlineBlock,
            inlineFlex,
            inlineGrid,
            invert,
            italic,
            items,
            justify,
            justifyItems,
            justifySelf,
            leading,
            left,
            lineClamp,
            lineThrough,
            listItem,
            listStyleImage,
            listStylePosition,
            listStyleType,
            lowercase,
            m,
            maxH,
            maxW,
            minH,
            minW,
            mixBlend,
            noUnderline,
            normalCase,
            object,
            objectPosition,
            opacity,
            order,
            origin,
            overflow,
            overflowX,
            overflowY,
            overline,
            overscroll,
            overscrollX,
            overscrollY,
            p,
            pb,
            pl,
            placeContent,
            placeItems,
            placeSelf,
            pointerEvents,
            position,
            pr,
            pt,
            px,
            py,
            relative,
            right,
            rotate,
            rounded,
            roundedB,
            roundedBl,
            roundedBr,
            roundedL,
            roundedR,
            roundedT,
            roundedTl,
            roundedTr,
            rowEnd,
            rowSpan,
            rowStart,
            saturate,
            scale,
            scrollBehavior,
            scrollM,
            scrollMB,
            scrollME,
            scrollML,
            scrollMR,
            scrollMS,
            scrollMT,
            scrollMX,
            scrollMY,
            scrollP,
            scrollPB,
            scrollPE,
            scrollPL,
            scrollPR,
            scrollPS,
            scrollPT,
            scrollPX,
            scrollPY,
            select,
            self,
            sepia,
            shadow,
            shadowColor,
            shrink,
            skewX,
            skewY,
            snapAlign,
            snapStop,
            snapType,
            sticky,
            table,
            text,
            textAlign,
            textClip,
            textEllipsis,
            textOverflow,
            textTransform,
            top,
            touch,
            tracking,
            transition,
            transitionTimingFunction,
            translateX,
            translateY,
            truncate,
            underline,
            underlineOffset,
            uppercase,
            visibility,
            w,
            whitespace,
            willChange,
            wordBreak,
            wrap,
            z,
            className,
          })
        )}
        ref={ref}
        {...props}
      />
    )
  }
)

Box.displayName = "Box"

export { Box }

// apps/kodi-svelte/src/components/primitives/Box.svelte
<script lang="ts">
	import type { BoxProps } from "./types"
	import { boxVariants } from "./variants"

	type $$Props = BoxProps & { as?: "div" | "h1" | "h2" | "h3" | "h4" | "p" | "span" }

	export let as: "div" | "h1" | "h2" | "h3" | "h4" | "p" | "span" = "div"
	//position
	export let position: Partial<$$Props>["position"] = undefined
	export let fixed: Partial<$$Props>["fixed"] = undefined
	export let absolute: Partial<$$Props>["absolute"] = undefined
	export let relative: Partial<$$Props>["relative"] = undefined
	export let sticky: Partial<$$Props>["sticky"] = undefined
	export let top: Partial<$$Props>["top"] = undefined
	export let bottom: Partial<$$Props>["bottom"] = undefined
	export let left: Partial<$$Props>["left"] = undefined
	export let right: Partial<$$Props>["right"] = undefined
	//display
	export let display: Partial<$$Props>["display"] = undefined
	export let flex: Partial<$$Props>["flex"] = undefined
	export let block: Partial<$$Props>["block"] = undefined
	export let inlineBlock: Partial<$$Props>["inlineBlock"] = undefined
	export let inline: Partial<$$Props>["inline"] = undefined
	export let grid: Partial<$$Props>["grid"] = undefined
	export let inlineGrid: Partial<$$Props>["inlineGrid"] = undefined
	export let listItem: Partial<$$Props>["listItem"] = undefined
	export let hidden: Partial<$$Props>["hidden"] = undefined
	//flex
	export let inlineFlex: Partial<$$Props>["inlineFlex"] = undefined
	export let contents: Partial<$$Props>["contents"] = undefined
	export let flexDirection: Partial<$$Props>["flexDirection"] = undefined
	export let wrap: Partial<$$Props>["wrap"] = undefined
	export let basis: Partial<$$Props>["basis"] = undefined
	export let grow: Partial<$$Props>["grow"] = undefined
	export let shrink: Partial<$$Props>["shrink"] = undefined
	//flex and grid
	export let order: Partial<$$Props>["order"] = undefined
	export let justify: Partial<$$Props>["justify"] = undefined
	export let content: Partial<$$Props>["content"] = undefined
	export let items: Partial<$$Props>["items"] = undefined
	export let self: Partial<$$Props>["self"] = undefined
	export let gap: Partial<$$Props>["gap"] = undefined
	export let gapX: Partial<$$Props>["gapX"] = undefined
	export let gapY: Partial<$$Props>["gapY"] = undefined
	//grid
	export let gridCols: Partial<$$Props>["gridCols"] = undefined
	export let colSpan: Partial<$$Props>["colSpan"] = undefined
	export let colStart: Partial<$$Props>["colStart"] = undefined
	export let colEnd: Partial<$$Props>["colEnd"] = undefined
	export let gridRows: Partial<$$Props>["gridRows"] = undefined
	export let rowSpan: Partial<$$Props>["rowSpan"] = undefined
	export let rowStart: Partial<$$Props>["rowStart"] = undefined
	export let rowEnd: Partial<$$Props>["rowEnd"] = undefined
	export let gridFlow: Partial<$$Props>["gridFlow"] = undefined
	export let autoCols: Partial<$$Props>["autoCols"] = undefined
	export let autoRows: Partial<$$Props>["autoRows"] = undefined
	export let justifyItems: Partial<$$Props>["justifyItems"] = undefined
	export let justifySelf: Partial<$$Props>["justifySelf"] = undefined
	export let placeContent: Partial<$$Props>["placeContent"] = undefined
	export let placeItems: Partial<$$Props>["placeItems"] = undefined
	export let placeSelf: Partial<$$Props>["placeSelf"] = undefined
	//spacing
	export let m: Partial<$$Props>["m"] = undefined
	export let p: Partial<$$Props>["p"] = undefined
	export let px: Partial<$$Props>["px"] = undefined
	export let py: Partial<$$Props>["py"] = undefined
	export let pt: Partial<$$Props>["pt"] = undefined
	export let pb: Partial<$$Props>["pb"] = undefined
	export let pl: Partial<$$Props>["pl"] = undefined
	export let pr: Partial<$$Props>["pr"] = undefined
	//layout
	export let aspect: Partial<$$Props>["aspect"] = undefined
	export let columns: Partial<$$Props>["columns"] = undefined
	export let floats: Partial<$$Props>["floats"] = undefined
	export let overflow: Partial<$$Props>["overflow"] = undefined
	export let overflowX: Partial<$$Props>["overflowX"] = undefined
	export let overflowY: Partial<$$Props>["overflowY"] = undefined
	export let visibility: Partial<$$Props>["visibility"] = undefined
	export let objectPosition: Partial<$$Props>["objectPosition"] = undefined
	export let object: Partial<$$Props>["object"] = undefined
	export let overscroll: Partial<$$Props>["overscroll"] = undefined
	export let overscrollX: Partial<$$Props>["overscrollX"] = undefined
	export let overscrollY: Partial<$$Props>["overscrollY"] = undefined
	export let z: Partial<$$Props>["z"] = undefined
	//sizes
	export let width: Partial<$$Props>["width"] = undefined
	export let minWidth: Partial<$$Props>["minWidth"] = undefined
	export let maxWidth: Partial<$$Props>["maxWidth"] = undefined
	export let height: Partial<$$Props>["height"] = undefined
	export let minHeight: Partial<$$Props>["minHeight"] = undefined
	export let maxHeight: Partial<$$Props>["maxHeight"] = undefined
	//borders
	export let borderColor: Partial<$$Props>["borderColor"] = undefined
	export let rounded: Partial<$$Props>["rounded"] = undefined
	export let roundedT: Partial<$$Props>["roundedT"] = undefined
	export let roundedB: Partial<$$Props>["roundedB"] = undefined
	export let roundedL: Partial<$$Props>["roundedL"] = undefined
	export let roundedR: Partial<$$Props>["roundedR"] = undefined
	export let roundedTl: Partial<$$Props>["roundedTl"] = undefined
	export let roundedTr: Partial<$$Props>["roundedTr"] = undefined
	export let roundedBl: Partial<$$Props>["roundedBl"] = undefined
	export let roundedBr: Partial<$$Props>["roundedBr"] = undefined
	export let borderWidth: Partial<$$Props>["borderWidth"] = undefined
	export let borderWidthX: Partial<$$Props>["borderWidthX"] = undefined
	export let borderWidthY: Partial<$$Props>["borderWidthY"] = undefined
	export let borderWidthT: Partial<$$Props>["borderWidthT"] = undefined
	export let borderWidthB: Partial<$$Props>["borderWidthB"] = undefined
	export let borderWidthL: Partial<$$Props>["borderWidthL"] = undefined
	export let borderWidthR: Partial<$$Props>["borderWidthR"] = undefined
	export let borderStyle: Partial<$$Props>["borderStyle"] = undefined
	//effects
	export let shadow: Partial<$$Props>["shadow"] = undefined
	export let shadowColor: Partial<$$Props>["shadowColor"] = undefined
	export let opacity: Partial<$$Props>["opacity"] = undefined
	export let mixBlend: Partial<$$Props>["mixBlend"] = undefined
	export let bgBlend: Partial<$$Props>["bgBlend"] = undefined
	//filters
	export let blur: Partial<$$Props>["blur"] = undefined
	export let brightness: Partial<$$Props>["brightness"] = undefined
	export let contrast: Partial<$$Props>["contrast"] = undefined
	export let dropShadow: Partial<$$Props>["dropShadow"] = undefined
	export let grayscale: Partial<$$Props>["grayscale"] = undefined
	export let hueRotate: Partial<$$Props>["hueRotate"] = undefined
	export let invert: Partial<$$Props>["invert"] = undefined
	export let saturate: Partial<$$Props>["saturate"] = undefined
	export let sepia: Partial<$$Props>["sepia"] = undefined
	export let backdropBlur: Partial<$$Props>["backdropBlur"] = undefined
	export let backdropBrightness: Partial<$$Props>["backdropBrightness"] = undefined
	export let backdropContrast: Partial<$$Props>["backdropContrast"] = undefined
	export let backdropGrayscale: Partial<$$Props>["backdropGrayscale"] = undefined
	export let backdropInvert: Partial<$$Props>["backdropInvert"] = undefined
	export let backdropOpacity: Partial<$$Props>["backdropOpacity"] = undefined
	export let backdropSaturate: Partial<$$Props>["backdropSaturate"] = undefined
	export let backdropSepia: Partial<$$Props>["backdropSepia"] = undefined
	// typography
	export let fontFamily: Partial<$$Props>["fontFamily"] = undefined
	export let fontSize: Partial<$$Props>["fontSize"] = undefined
	export let fontSmoothing: Partial<$$Props>["fontSmoothing"] = undefined
	export let italic: Partial<$$Props>["italic"] = undefined
	export let fontStyle: Partial<$$Props>["fontStyle"] = undefined
	export let fontWeight: Partial<$$Props>["fontWeight"] = undefined
	export let fontVariantNumeric: Partial<$$Props>["fontVariantNumeric"] = undefined
	export let tracking: Partial<$$Props>["tracking"] = undefined
	export let lineClamp: Partial<$$Props>["lineClamp"] = undefined
	export let leading: Partial<$$Props>["leading"] = undefined
	export let listStyleImage: Partial<$$Props>["listStyleImage"] = undefined
	export let listStylePosition: Partial<$$Props>["listStylePosition"] = undefined
	export let listStyleType: Partial<$$Props>["listStyleType"] = undefined
	export let textAlign: Partial<$$Props>["textAlign"] = undefined
	export let underline: Partial<$$Props>["underline"] = undefined
	export let overline: Partial<$$Props>["overline"] = undefined
	export let lineThrough: Partial<$$Props>["lineThrough"] = undefined
	export let noUnderline: Partial<$$Props>["noUnderline"] = undefined
	export let decoration: Partial<$$Props>["decoration"] = undefined
	export let decorationStyle: Partial<$$Props>["decorationStyle"] = undefined
	export let decorationThickness: Partial<$$Props>["decorationThickness"] = undefined
	export let underlineOffset: Partial<$$Props>["underlineOffset"] = undefined
	export let uppercase: Partial<$$Props>["uppercase"] = undefined
	export let lowercase: Partial<$$Props>["lowercase"] = undefined
	export let capitalize: Partial<$$Props>["capitalize"] = undefined
	export let normalCase: Partial<$$Props>["normalCase"] = undefined
	export let textTransform: Partial<$$Props>["textTransform"] = undefined
	export let truncate: Partial<$$Props>["truncate"] = undefined
	export let textEllipsis: Partial<$$Props>["textEllipsis"] = undefined
	export let textClip: Partial<$$Props>["textClip"] = undefined
	export let textOverflow: Partial<$$Props>["textOverflow"] = undefined
	export let align: Partial<$$Props>["align"] = undefined
	export let whitespace: Partial<$$Props>["whitespace"] = undefined
	export let wordBreak: Partial<$$Props>["wordBreak"] = undefined
	export let hyphens: Partial<$$Props>["hyphens"] = undefined
	export let indent: Partial<$$Props>["indent"] = undefined
	export let decorationColor: Partial<$$Props>["decorationColor"] = undefined
	export let text: Partial<$$Props>["text"] = undefined
	//backgrounds
	export let bg: Partial<$$Props>["bg"] = undefined
	export let bgAttachment: Partial<$$Props>["bgAttachment"] = undefined
	export let bgClip: Partial<$$Props>["bgClip"] = undefined
	export let bgOrigin: Partial<$$Props>["bgOrigin"] = undefined
	export let bgPosition: Partial<$$Props>["bgPosition"] = undefined
	export let bgRepeat: Partial<$$Props>["bgRepeat"] = undefined
	export let bgSize: Partial<$$Props>["bgSize"] = undefined
	export let bgImage: Partial<$$Props>["bgImage"] = undefined
	export let gradientFromStop: Partial<$$Props>["gradientFromStop"] = undefined
	export let gradientToStop: Partial<$$Props>["gradientToStop"] = undefined
	export let gradientViaStop: Partial<$$Props>["gradientViaStop"] = undefined
	//transitions, transforms and animations
	export let transition: Partial<$$Props>["transition"] = undefined
	export let duration: Partial<$$Props>["duration"] = undefined
	export let transitionTimingFunction: Partial<$$Props>["transitionTimingFunction"] = undefined
	export let delay: Partial<$$Props>["delay"] = undefined
	export let scale: Partial<$$Props>["scale"] = undefined
	export let rotate: Partial<$$Props>["rotate"] = undefined
	export let translateX: Partial<$$Props>["translateX"] = undefined
	export let translateY: Partial<$$Props>["translateY"] = undefined
	export let skewX: Partial<$$Props>["skewX"] = undefined
	export let skewY: Partial<$$Props>["skewY"] = undefined
	export let origin: Partial<$$Props>["origin"] = undefined
	//table
	export let borderCollapse: Partial<$$Props>["borderCollapse"] = undefined
	export let borderSpacing: Partial<$$Props>["borderSpacing"] = undefined
	export let borderSpacingX: Partial<$$Props>["borderSpacingX"] = undefined
	export let borderSpacingY: Partial<$$Props>["borderSpacingY"] = undefined
	export let table: Partial<$$Props>["table"] = undefined
	export let caption: Partial<$$Props>["caption"] = undefined
	//interactivity
	export let cursor: Partial<$$Props>["cursor"] = undefined
	export let pointerEvents: Partial<$$Props>["pointerEvents"] = undefined
	export let scrollBehavior: Partial<$$Props>["scrollBehavior"] = undefined
	export let snapAlign: Partial<$$Props>["snapAlign"] = undefined
	export let snapStop: Partial<$$Props>["snapStop"] = undefined
	export let snapType: Partial<$$Props>["snapType"] = undefined
	export let touch: Partial<$$Props>["touch"] = undefined
	export let select: Partial<$$Props>["select"] = undefined
	export let willChange: Partial<$$Props>["willChange"] = undefined
	export let scrollM: Partial<$$Props>["scrollM"] = undefined
	export let scrollMX: Partial<$$Props>["scrollMX"] = undefined
	export let scrollMY: Partial<$$Props>["scrollMY"] = undefined
	export let scrollMS: Partial<$$Props>["scrollMS"] = undefined
	export let scrollME: Partial<$$Props>["scrollME"] = undefined
	export let scrollMT: Partial<$$Props>["scrollMT"] = undefined
	export let scrollMB: Partial<$$Props>["scrollMB"] = undefined
	export let scrollML: Partial<$$Props>["scrollML"] = undefined
	export let scrollMR: Partial<$$Props>["scrollMR"] = undefined
	export let scrollP: Partial<$$Props>["scrollP"] = undefined
	export let scrollPX: Partial<$$Props>["scrollPX"] = undefined
	export let scrollPY: Partial<$$Props>["scrollPY"] = undefined
	export let scrollPS: Partial<$$Props>["scrollPS"] = undefined
	export let scrollPE: Partial<$$Props>["scrollPE"] = undefined
	export let scrollPT: Partial<$$Props>["scrollPT"] = undefined
	export let scrollPB: Partial<$$Props>["scrollPB"] = undefined
	export let scrollPL: Partial<$$Props>["scrollPL"] = undefined
	export let scrollPR: Partial<$$Props>["scrollPR"] = undefined
</script>

<svelte:element
	this={as}
	class={boxVariants({
		position,
		fixed,
		absolute,
		relative,
		sticky,
		top,
		bottom,
		left,
		right,
		display,
		block,
		inlineBlock,
		inlineFlex,
		contents,
		inline,
		grid,
		inlineGrid,
		listItem,
		hidden,
		flex,
		flexDirection,
		wrap,
		justify,
		basis,
		grow,
		shrink,
		order,
		content,
		items,
		self,
		gap,
		gapX,
		gapY,
		p,
		px,
		py,
		pt,
		pb,
		pl,
		pr,
		m,
		overflow,
		overflowX,
		overflowY,
		visibility,
		z,
		object,
		objectPosition,
		overscroll,
		overscrollX,
		overscrollY,
		width,
		minWidth,
		maxWidth,
		height,
		minHeight,
		maxHeight,
		text,
		borderColor,
		rounded,
		roundedT,
		roundedB,
		roundedL,
		roundedR,
		roundedTl,
		roundedTr,
		roundedBl,
		roundedBr,
		borderWidth,
		borderWidthX,
		borderWidthY,
		borderWidthT,
		borderWidthB,
		borderWidthL,
		borderWidthR,
		borderStyle,
		shadow,
		shadowColor,
		opacity,
		mixBlend,
		bgBlend,
		blur,
		brightness,
		contrast,
		dropShadow,
		grayscale,
		hueRotate,
		invert,
		saturate,
		sepia,
		backdropBlur,
		backdropBrightness,
		backdropContrast,
		backdropGrayscale,
		backdropInvert,
		backdropOpacity,
		backdropSaturate,
		backdropSepia,
		fontFamily,
		fontSize,
		fontSmoothing,
		italic,
		fontStyle,
		fontWeight,
		fontVariantNumeric,
		tracking,
		lineClamp,
		leading,
		listStyleImage,
		listStylePosition,
		listStyleType,
		textAlign,
		underline,
		overline,
		lineThrough,
		noUnderline,
		decoration,
		decorationStyle,
		decorationThickness,
		underlineOffset,
		uppercase,
		lowercase,
		capitalize,
		normalCase,
		textTransform,
		truncate,
		textEllipsis,
		textClip,
		textOverflow,
		indent,
		align,
		whitespace,
		wordBreak,
		hyphens,
		decorationColor,
		bg,
		bgAttachment,
		bgClip,
		bgOrigin,
		bgPosition,
		bgRepeat,
		bgSize,
		bgImage,
		gradientFromStop,
		gradientViaStop,
		gradientToStop,
		transition,
		duration,
		transitionTimingFunction,
		delay,
		scale,
		rotate,
		translateX,
		translateY,
		skewX,
		skewY,
		origin,
		gridCols,
		colSpan,
		colStart,
		colEnd,
		gridRows,
		rowSpan,
		rowStart,
		rowEnd,
		gridFlow,
		autoCols,
		autoRows,
		justifyItems,
		justifySelf,
		placeContent,
		placeItems,
		placeSelf,
		borderCollapse,
		borderSpacing,
		borderSpacingX,
		borderSpacingY,
		table,
		caption,
		aspect,
		columns,
		floats,
		cursor,
		pointerEvents,
		scrollBehavior,
		snapAlign,
		snapStop,
		snapType,
		touch,
		select,
		willChange,
		scrollM,
		scrollMX,
		scrollMY,
		scrollMS,
		scrollME,
		scrollMT,
		scrollMB,
		scrollML,
		scrollMR,
		scrollP,
		scrollPX,
		scrollPY,
		scrollPS,
		scrollPE,
		scrollPT,
		scrollPB,
		scrollPL,
		scrollPR,
		class: $$props.class,
	})}
>
	<slot />
</svelte:element>
